export const ProjectsData = [
  {
    name: "Chat PDF",
    description: "This is the project description",
    image: "/images/chatpdf.jpg",
    techStack: ["Next.js", "OpenAI", "Clerk", "NeonDB", "Stripe", "AWS"],
    link: "url link",
  },
  {
    name: "Easy Cook",
    description: "This is the project descriptionThis is the project descriptionThis is the project descriptionThis is the project descriptionv",
    image: "/images/project-image.jpg",
    techStack: ["Next.js", "OpenAI", "Clerk", "NeonDB", "Stripe", "AWS "],
    link: "url link",
  },
  {
    name: "Project name 3",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: ["aaaa", "bbbb", "cccc", "dddd"],
    link: "url link",
  },
  {
    name: "Project name",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: ["aaaa", "bbbb", "cccc", "dddd"],
    link: "url link",
  },
  {
    name: "Project name 2",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: ["aaaa", "bbbb", "cccc", "dddd"],
    link: "url link",
  },
  {
    name: "Project name 3",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: ["aaaa", "bbbb", "cccc", "dddd"],
    link: "url link",
  },
  {
    name: "Project name",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: ["aaaa", "bbbb", "cccc", "dddd"],
    link: "url link",
  },
  {
    name: "Project name 2",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: ["aaaa", "bbbb", "cccc", "dddd"],
    link: "url link",
  },
  {
    name: "Project name 3",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: ["aaaa", "bbbb", "cccc", "dddd"],
    link: "url link",
  },
];
