export const ProjectsData = [
  {
    name: "Chat PDF",
    description: "Upload a PDF and chat with the AI to summarize the content",
    image: "/images/chatpdf.jpg",
    techStackDisplay: ["Next.js", "OpenAI", "Clerk", "NeonDB", "AWS", "..."],
    techStack: ["Next.js", "OpenAI", "Clerk", "NeonDB", "Stripe", "AWS", "TypeScript", "Stripe", "TailwindCSS"],
    link: "https://github.com/StevenJSCF/chatpdf",
  },
  {
    name: "Easy Cook",
    description: "Use Ai to create recipes, based on the ingredients you have",
    image: "/images/easycook.png",
    techStackDisplay: ["Next.js", "OpenAI", "Clerk", "MongoDB", "Stripe", "...",],
    techStack: ["Next.js", "OpenAI", "Clerk", "NeonDB", "Stripe", "AWS", "TypeScript", "TailwindCSS"],
    link: "https://github.com/StevenJSCF/EasyCook-",
  },
  {
    name: "Maze Ball Game",
    description: "Mobile app game inspirated from the popular game (Where's My Water) This engaging game allows players to chat, collaboratively craft new maps in real-time with friends, and engage in multiplayer gameplay against other participants.",
    image: "/images/mazeball.png",
    techStackDisplay: ["Android Studio", "SpringBoot", "MySQL","Java"],
    techStack: ["Android Studio", "SpringBoot", "MySQL", "Java"],
    link: "https://github.com/StevenJSCF/MazeBall-MobileApp-Game",
  },
  {
    name: "Pokemon Game",
    description: "ASCII Pokemon-inspired roguelike built with C and C++, combining turn-based role-playing elements of both Pokemon and roguelike games. The game features a retro aesthetic, presented entirely in ASCII graphics within a terminal interface.",
    image: "/images/pokemon-game.png",
    techStackDisplay: ["C", "C++"],
    techStack: ["C", "C++"],
    link: "https://github.com/StevenJSCF/Pokemon-game",
  },
  {
    name: "Project name 2",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStackDisplay: ["Next.js", "OpenAI", "Clerk", "NeonDB", "Stripe", "AWS",],
    techStack: ["aaaa", "bbbb", "cccc", "dddd"],
    link: "url link",
  },
  {
    name: "Project name 3",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStackDisplay: ["Next.js", "OpenAI", "Clerk", "NeonDB", "Stripe", "AWS",],
    techStack: ["aaaa", "bbbb", "cccc", "dddd"],
    link: "url link",
  },
  {
    name: "Project name",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStackDisplay: ["Next.js", "OpenAI", "Clerk", "NeonDB", "Stripe", "AWS",],
    techStack: ["aaaa", "bbbb", "cccc", "dddd"],
    link: "url link",
  },
  {
    name: "Project name 2",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStackDisplay: ["Next.js", "OpenAI", "Clerk", "NeonDB", "Stripe", "AWS",],
    techStack: ["aaaa", "bbbb", "cccc", "dddd"],
    link: "url link",
  },
  {
    name: "Project name 3",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStackDisplay: ["Next.js", "OpenAI", "Clerk", "NeonDB", "Stripe", "AWS",],
    techStack: ["aaaa", "bbbb", "cccc", "dddd"],
    link: "url link",
  },
];
