export const ProjectsData = [
  {
    name: "Project name",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: "a,b,c,d,",
    link: "url link",
  },
  {
    name: "Project name 2",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: "a,b,c,d,",
    link: "url link",
  },
  {
    name: "Project name 3",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: "a,b,c,d,",
    link: "url link",
  },
  {
    name: "Project name",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: "a,b,c,d,",
    link: "url link",
  },
  {
    name: "Project name 2",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: "a,b,c,d,",
    link: "url link",
  },
  {
    name: "Project name 3",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: "a,b,c,d,",
    link: "url link",
  },
  {
    name: "Project name",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: "a,b,c,d,",
    link: "url link",
  },
  {
    name: "Project name 2",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: "a,b,c,d,",
    link: "url link",
  },
  {
    name: "Project name 3",
    description: "This is the project description",
    image: "/images/project-image.jpg",
    techStack: "a,b,c,d,",
    link: "url link",
  },
];
